// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Research.Domain.Context;

#nullable disable

namespace Research.Domain.Migrations
{
    [DbContext(typeof(ResearchContext))]
    [Migration("20220608114903_addedData")]
    partial class addedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Research.Domain.Entity.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("b9ce3cf4-365e-4dea-817c-8d04b5746aa0"),
                            Code = 1,
                            Description = "English"
                        },
                        new
                        {
                            LanguageId = new Guid("c915c0d9-830e-447c-a722-bee0ebb4cb36"),
                            Code = 2,
                            Description = "French"
                        },
                        new
                        {
                            LanguageId = new Guid("b966f909-0bed-4f0c-b7dd-89dd72cfbd13"),
                            Code = 3,
                            Description = "German"
                        },
                        new
                        {
                            LanguageId = new Guid("811c9b2e-4b81-4dba-8b01-597f4b2b1d01"),
                            Code = 4,
                            Description = "Spanish"
                        },
                        new
                        {
                            LanguageId = new Guid("500aef74-4334-43b9-8225-e4d58f2d26fc"),
                            Code = 5,
                            Description = "Italian"
                        },
                        new
                        {
                            LanguageId = new Guid("beadbad9-106d-4d69-bddf-86394bee456e"),
                            Code = 6,
                            Description = "Portuguese"
                        },
                        new
                        {
                            LanguageId = new Guid("3a6f9d35-af6a-48bf-b115-53b93cf8eb90"),
                            Code = 7,
                            Description = "Russian"
                        });
                });

            modelBuilder.Entity("Research.Domain.Entity.LanguageLevel", b =>
                {
                    b.Property<Guid>("LanguageLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageLevelId");

                    b.ToTable("LanguageLevel");

                    b.HasData(
                        new
                        {
                            LanguageLevelId = new Guid("6cfb9163-c449-4036-abb8-e23bec855d28"),
                            Code = 1,
                            Description = "Beginner"
                        },
                        new
                        {
                            LanguageLevelId = new Guid("78413890-f8d4-4d86-8adf-e8fc31d9f7ea"),
                            Code = 2,
                            Description = "Elementary"
                        },
                        new
                        {
                            LanguageLevelId = new Guid("53dc146a-d301-406a-8e88-a06b310a90ce"),
                            Code = 3,
                            Description = "Pre-Intermediate"
                        },
                        new
                        {
                            LanguageLevelId = new Guid("5e4ba351-fd4e-4abc-a437-b71225f5b3f3"),
                            Code = 4,
                            Description = "Intermediate"
                        },
                        new
                        {
                            LanguageLevelId = new Guid("49cd01f7-bc20-406c-98cf-c520687bd21b"),
                            Code = 5,
                            Description = "Upper-Intermediate"
                        },
                        new
                        {
                            LanguageLevelId = new Guid("0c0fe95c-4726-4a7e-a673-895f5049e087"),
                            Code = 6,
                            Description = "Advanced"
                        });
                });

            modelBuilder.Entity("Research.Domain.Entity.LanguageLink", b =>
                {
                    b.Property<Guid>("LanguageLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LanguageLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Preferred")
                        .HasColumnType("bit");

                    b.HasKey("LanguageLinkId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguageLevelId");

                    b.HasIndex("PersonId");

                    b.ToTable("LanguageLink");

                    b.HasData(
                        new
                        {
                            LanguageLinkId = new Guid("0cbb2375-fee8-4a41-a5a5-905b738e2400"),
                            LanguageId = new Guid("b9ce3cf4-365e-4dea-817c-8d04b5746aa0"),
                            LanguageLevelId = new Guid("53dc146a-d301-406a-8e88-a06b310a90ce"),
                            PersonId = new Guid("238ee722-430f-4936-80c1-017723073961"),
                            Preferred = true
                        },
                        new
                        {
                            LanguageLinkId = new Guid("80d3fcf7-fd16-442b-a453-d4dac2a7b24a"),
                            LanguageId = new Guid("c915c0d9-830e-447c-a722-bee0ebb4cb36"),
                            LanguageLevelId = new Guid("0c0fe95c-4726-4a7e-a673-895f5049e087"),
                            PersonId = new Guid("238ee722-430f-4936-80c1-017723073961"),
                            Preferred = false
                        },
                        new
                        {
                            LanguageLinkId = new Guid("4217c122-216d-43b2-a7f4-d2fba97bd42a"),
                            LanguageId = new Guid("b966f909-0bed-4f0c-b7dd-89dd72cfbd13"),
                            LanguageLevelId = new Guid("6cfb9163-c449-4036-abb8-e23bec855d28"),
                            PersonId = new Guid("c78a80d8-d13c-44f9-a511-21674f628826"),
                            Preferred = true
                        },
                        new
                        {
                            LanguageLinkId = new Guid("29021107-ca2e-45fc-87ea-57f558c95734"),
                            LanguageId = new Guid("811c9b2e-4b81-4dba-8b01-597f4b2b1d01"),
                            LanguageLevelId = new Guid("78413890-f8d4-4d86-8adf-e8fc31d9f7ea"),
                            PersonId = new Guid("c78a80d8-d13c-44f9-a511-21674f628826"),
                            Preferred = false
                        },
                        new
                        {
                            LanguageLinkId = new Guid("6eeed4ed-78c2-4819-99e4-e0d43164f3da"),
                            LanguageId = new Guid("500aef74-4334-43b9-8225-e4d58f2d26fc"),
                            LanguageLevelId = new Guid("53dc146a-d301-406a-8e88-a06b310a90ce"),
                            PersonId = new Guid("7790e89c-5ed3-470b-9a61-052c2881cba5"),
                            Preferred = true
                        },
                        new
                        {
                            LanguageLinkId = new Guid("bff76a59-db06-4390-9660-6ef2f89c1fc7"),
                            LanguageId = new Guid("beadbad9-106d-4d69-bddf-86394bee456e"),
                            LanguageLevelId = new Guid("5e4ba351-fd4e-4abc-a437-b71225f5b3f3"),
                            PersonId = new Guid("7790e89c-5ed3-470b-9a61-052c2881cba5"),
                            Preferred = false
                        },
                        new
                        {
                            LanguageLinkId = new Guid("711605f9-dbbc-40d6-a05b-9f06b61d8d1e"),
                            LanguageId = new Guid("3a6f9d35-af6a-48bf-b115-53b93cf8eb90"),
                            LanguageLevelId = new Guid("49cd01f7-bc20-406c-98cf-c520687bd21b"),
                            PersonId = new Guid("f96d5032-cdbc-46e4-adba-f63046c49e8b"),
                            Preferred = true
                        });
                });

            modelBuilder.Entity("Research.Domain.Entity.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<bool>("IsRecruiter")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Remote")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Surnamme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.HasIndex("SiteId");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("238ee722-430f-4936-80c1-017723073961"),
                            Code = 1,
                            IsRecruiter = false,
                            Name = "Nicoletta",
                            Position = "dev",
                            Remote = false,
                            SiteId = new Guid("57dfe520-ee12-4c61-b9a8-94a78353dfb4"),
                            Surnamme = "Morsia",
                            YearsOfExperience = 2
                        },
                        new
                        {
                            PersonId = new Guid("c78a80d8-d13c-44f9-a511-21674f628826"),
                            Code = 2,
                            IsRecruiter = true,
                            Name = "Mario",
                            Position = "recuiter",
                            Remote = true,
                            SiteId = new Guid("09168b51-310d-4f50-9036-878e93203df6"),
                            Surnamme = "Rossi",
                            YearsOfExperience = 2
                        },
                        new
                        {
                            PersonId = new Guid("7790e89c-5ed3-470b-9a61-052c2881cba5"),
                            Code = 3,
                            IsRecruiter = true,
                            Name = "Mario",
                            Position = "recruiter",
                            Remote = false,
                            SiteId = new Guid("57dfe520-ee12-4c61-b9a8-94a78353dfb4"),
                            Surnamme = "Rossi",
                            YearsOfExperience = 2
                        },
                        new
                        {
                            PersonId = new Guid("f96d5032-cdbc-46e4-adba-f63046c49e8b"),
                            Code = 4,
                            IsRecruiter = false,
                            Name = "Mario",
                            Position = "dev",
                            Remote = true,
                            SiteId = new Guid("57dfe520-ee12-4c61-b9a8-94a78353dfb4"),
                            Surnamme = "Rossi",
                            YearsOfExperience = 2
                        },
                        new
                        {
                            PersonId = new Guid("702907dd-3a80-4b4e-98c6-9adaa82d6aab"),
                            Code = 5,
                            IsRecruiter = false,
                            Name = "Giovanni",
                            Position = "dev",
                            Remote = true,
                            SiteId = new Guid("005fe637-637d-4239-94c3-1a2ce756c439"),
                            Surnamme = "Bianchi",
                            YearsOfExperience = 4
                        },
                        new
                        {
                            PersonId = new Guid("cd52721a-8579-4cdb-899a-50694e35cd49"),
                            Code = 6,
                            IsRecruiter = false,
                            Name = "Alessandra",
                            Position = "dev",
                            Remote = true,
                            SiteId = new Guid("09168b51-310d-4f50-9036-878e93203df6"),
                            Surnamme = "Verdi",
                            YearsOfExperience = 15
                        },
                        new
                        {
                            PersonId = new Guid("5e770d60-4689-4b80-b600-64eed4205a6a"),
                            Code = 7,
                            IsRecruiter = false,
                            Name = "Giovanni",
                            Position = "dev",
                            Remote = true,
                            SiteId = new Guid("0b9478ca-2e7e-4968-9ca8-7192455a3f76"),
                            Surnamme = "Novembre",
                            YearsOfExperience = 1
                        });
                });

            modelBuilder.Entity("Research.Domain.Entity.Research", b =>
                {
                    b.Property<Guid>("ResearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Remote")
                        .HasColumnType("bit");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResearchId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SiteId");

                    b.ToTable("Research");

                    b.HasData(
                        new
                        {
                            ResearchId = new Guid("ebfe0954-80db-487d-b6fb-66b422b5c687"),
                            Code = 1,
                            Description = "Front end Angular",
                            LanguageId = new Guid("b9ce3cf4-365e-4dea-817c-8d04b5746aa0"),
                            PersonId = new Guid("c78a80d8-d13c-44f9-a511-21674f628826"),
                            Remote = true,
                            SiteId = new Guid("57dfe520-ee12-4c61-b9a8-94a78353dfb4")
                        },
                        new
                        {
                            ResearchId = new Guid("f362086e-758a-474f-b2ef-57af4fe90f31"),
                            Code = 2,
                            Description = "Back end .NET",
                            LanguageId = new Guid("c915c0d9-830e-447c-a722-bee0ebb4cb36"),
                            PersonId = new Guid("c78a80d8-d13c-44f9-a511-21674f628826"),
                            Remote = true,
                            SiteId = new Guid("09168b51-310d-4f50-9036-878e93203df6")
                        },
                        new
                        {
                            ResearchId = new Guid("3dcd8502-0902-4816-a151-f6c6c2a0b7cc"),
                            Code = 3,
                            Description = "Typescript",
                            LanguageId = new Guid("b9ce3cf4-365e-4dea-817c-8d04b5746aa0"),
                            PersonId = new Guid("c78a80d8-d13c-44f9-a511-21674f628826"),
                            Remote = true,
                            SiteId = new Guid("005fe637-637d-4239-94c3-1a2ce756c439")
                        },
                        new
                        {
                            ResearchId = new Guid("bfb5446d-f1df-4ae2-88df-74a3698c4944"),
                            Code = 4,
                            Description = "Azure",
                            LanguageId = new Guid("b966f909-0bed-4f0c-b7dd-89dd72cfbd13"),
                            PersonId = new Guid("c78a80d8-d13c-44f9-a511-21674f628826"),
                            Remote = false,
                            SiteId = new Guid("78fee931-b61d-4732-b637-9cc58c1c02ed")
                        },
                        new
                        {
                            ResearchId = new Guid("f021f51f-33b3-4668-a55e-b7e541b4b110"),
                            Code = 5,
                            Description = "Smss",
                            LanguageId = new Guid("811c9b2e-4b81-4dba-8b01-597f4b2b1d01"),
                            PersonId = new Guid("c78a80d8-d13c-44f9-a511-21674f628826"),
                            Remote = false,
                            SiteId = new Guid("0b9478ca-2e7e-4968-9ca8-7192455a3f76")
                        },
                        new
                        {
                            ResearchId = new Guid("4f8b05ff-33dc-412e-ad45-a62c01443db0"),
                            Code = 6,
                            Description = "Back end .NET",
                            LanguageId = new Guid("500aef74-4334-43b9-8225-e4d58f2d26fc"),
                            PersonId = new Guid("7790e89c-5ed3-470b-9a61-052c2881cba5"),
                            Remote = true,
                            SiteId = new Guid("09168b51-310d-4f50-9036-878e93203df6")
                        },
                        new
                        {
                            ResearchId = new Guid("c18ff02c-1aa4-4eb1-a773-fe04c0cc215c"),
                            Code = 7,
                            Description = "Azure",
                            LanguageId = new Guid("811c9b2e-4b81-4dba-8b01-597f4b2b1d01"),
                            PersonId = new Guid("7790e89c-5ed3-470b-9a61-052c2881cba5"),
                            Remote = true,
                            SiteId = new Guid("78fee931-b61d-4732-b637-9cc58c1c02ed")
                        },
                        new
                        {
                            ResearchId = new Guid("1e3d0b39-fe87-425a-8697-ef8b5d53f4eb"),
                            Code = 8,
                            Description = "Flutter",
                            LanguageId = new Guid("beadbad9-106d-4d69-bddf-86394bee456e"),
                            PersonId = new Guid("7790e89c-5ed3-470b-9a61-052c2881cba5"),
                            Remote = true,
                            SiteId = new Guid("57dfe520-ee12-4c61-b9a8-94a78353dfb4")
                        },
                        new
                        {
                            ResearchId = new Guid("cb8784dd-332b-40c1-bff5-5b784a908648"),
                            Code = 9,
                            Description = "Back end .NET",
                            LanguageId = new Guid("3a6f9d35-af6a-48bf-b115-53b93cf8eb90"),
                            PersonId = new Guid("7790e89c-5ed3-470b-9a61-052c2881cba5"),
                            Remote = true,
                            SiteId = new Guid("0b9478ca-2e7e-4968-9ca8-7192455a3f76")
                        });
                });

            modelBuilder.Entity("Research.Domain.Entity.Site", b =>
                {
                    b.Property<Guid>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiteId");

                    b.ToTable("Site");

                    b.HasData(
                        new
                        {
                            SiteId = new Guid("57dfe520-ee12-4c61-b9a8-94a78353dfb4"),
                            Code = 1,
                            Description = "NEW YORK"
                        },
                        new
                        {
                            SiteId = new Guid("09168b51-310d-4f50-9036-878e93203df6"),
                            Code = 2,
                            Description = "CHICAGO"
                        },
                        new
                        {
                            SiteId = new Guid("005fe637-637d-4239-94c3-1a2ce756c439"),
                            Code = 3,
                            Description = "WASHINGTON"
                        },
                        new
                        {
                            SiteId = new Guid("78fee931-b61d-4732-b637-9cc58c1c02ed"),
                            Code = 4,
                            Description = "LOS ANGELES"
                        },
                        new
                        {
                            SiteId = new Guid("0b9478ca-2e7e-4968-9ca8-7192455a3f76"),
                            Code = 5,
                            Description = "LONDON"
                        });
                });

            modelBuilder.Entity("Research.Domain.Entity.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FEBEDevops")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebMobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.ToTable("Skill");

                    b.HasData(
                        new
                        {
                            SkillId = new Guid("79cd2fdd-1158-4442-a916-5ea969cb21ac"),
                            Code = 1,
                            Description = "Angular 9",
                            FEBEDevops = "",
                            ProjectRef = "",
                            Technology = "",
                            WebMobile = "angular"
                        },
                        new
                        {
                            SkillId = new Guid("7f9b6ec1-ae0e-417c-80c8-4c80e6270274"),
                            Code = 2,
                            Description = "TS",
                            FEBEDevops = "",
                            ProjectRef = "",
                            Technology = "",
                            WebMobile = "typescript"
                        },
                        new
                        {
                            SkillId = new Guid("76cfa6ae-48bc-457c-bda4-001dc66b80a7"),
                            Code = 3,
                            Description = "Azure",
                            FEBEDevops = "Azure",
                            ProjectRef = "",
                            Technology = "",
                            WebMobile = ""
                        },
                        new
                        {
                            SkillId = new Guid("aa55f60e-d599-4672-b3c7-788b87a763c0"),
                            Code = 4,
                            Description = "Flutter",
                            FEBEDevops = "",
                            ProjectRef = "",
                            Technology = "",
                            WebMobile = "Flutter"
                        },
                        new
                        {
                            SkillId = new Guid("4cdc25b2-d989-4b08-a403-1d4d25bf38b7"),
                            Code = 5,
                            Description = "Iot",
                            FEBEDevops = "",
                            ProjectRef = "",
                            Technology = "Iot",
                            WebMobile = ""
                        },
                        new
                        {
                            SkillId = new Guid("2f4fbd0f-97bf-4c9e-bc30-61c18658f338"),
                            Code = 6,
                            Description = ".NET",
                            FEBEDevops = ".NET",
                            ProjectRef = "",
                            Technology = "",
                            WebMobile = ""
                        },
                        new
                        {
                            SkillId = new Guid("035bfc8a-c8dd-46ce-9c9f-39ecb0a2a8fe"),
                            Code = 7,
                            Description = "SMSS",
                            FEBEDevops = "",
                            ProjectRef = "",
                            Technology = "SSMS",
                            WebMobile = ""
                        });
                });

            modelBuilder.Entity("Research.Domain.Entity.SkillLink", b =>
                {
                    b.Property<Guid>("SkillLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SkillLinkId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillLink");

                    b.HasData(
                        new
                        {
                            SkillLinkId = new Guid("8a45bf46-4cf0-44b8-bebe-e00a49d99496"),
                            Level = 1,
                            PersonId = new Guid("238ee722-430f-4936-80c1-017723073961"),
                            SkillId = new Guid("79cd2fdd-1158-4442-a916-5ea969cb21ac")
                        },
                        new
                        {
                            SkillLinkId = new Guid("27ee3007-d32f-4147-b6fa-3b19ca68aa06"),
                            Level = 2,
                            PersonId = new Guid("238ee722-430f-4936-80c1-017723073961"),
                            SkillId = new Guid("7f9b6ec1-ae0e-417c-80c8-4c80e6270274")
                        },
                        new
                        {
                            SkillLinkId = new Guid("f568c356-cfdf-4d9c-99c7-a090f081ba71"),
                            Level = 3,
                            PersonId = new Guid("c78a80d8-d13c-44f9-a511-21674f628826"),
                            SkillId = new Guid("76cfa6ae-48bc-457c-bda4-001dc66b80a7")
                        },
                        new
                        {
                            SkillLinkId = new Guid("213a5dea-8325-4a90-9429-f070d5b51c55"),
                            Level = 1,
                            PersonId = new Guid("7790e89c-5ed3-470b-9a61-052c2881cba5"),
                            SkillId = new Guid("aa55f60e-d599-4672-b3c7-788b87a763c0")
                        },
                        new
                        {
                            SkillLinkId = new Guid("01012ed8-e893-4fbd-a98f-3f02ebc18a4f"),
                            Level = 6,
                            PersonId = new Guid("f96d5032-cdbc-46e4-adba-f63046c49e8b"),
                            SkillId = new Guid("4cdc25b2-d989-4b08-a403-1d4d25bf38b7")
                        },
                        new
                        {
                            SkillLinkId = new Guid("b848a613-7dbc-4b99-a4c6-5afe2e50843e"),
                            Level = 3,
                            PersonId = new Guid("f96d5032-cdbc-46e4-adba-f63046c49e8b"),
                            SkillId = new Guid("2f4fbd0f-97bf-4c9e-bc30-61c18658f338")
                        },
                        new
                        {
                            SkillLinkId = new Guid("f7f145e2-b5f1-4990-afaf-3bc0ec879569"),
                            Level = 2,
                            PersonId = new Guid("f96d5032-cdbc-46e4-adba-f63046c49e8b"),
                            SkillId = new Guid("76cfa6ae-48bc-457c-bda4-001dc66b80a7")
                        },
                        new
                        {
                            SkillLinkId = new Guid("fa1274a5-0ed0-4299-9afb-0f43e8fb5789"),
                            Level = 2,
                            PersonId = new Guid("702907dd-3a80-4b4e-98c6-9adaa82d6aab"),
                            SkillId = new Guid("035bfc8a-c8dd-46ce-9c9f-39ecb0a2a8fe")
                        });
                });

            modelBuilder.Entity("Research.Domain.Entity.LanguageLink", b =>
                {
                    b.HasOne("Research.Domain.Entity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Research.Domain.Entity.LanguageLevel", "LanguageLevel")
                        .WithMany()
                        .HasForeignKey("LanguageLevelId");

                    b.HasOne("Research.Domain.Entity.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("LanguageLevel");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Research.Domain.Entity.Person", b =>
                {
                    b.HasOne("Research.Domain.Entity.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Research.Domain.Entity.Research", b =>
                {
                    b.HasOne("Research.Domain.Entity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Research.Domain.Entity.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Research.Domain.Entity.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Person");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Research.Domain.Entity.SkillLink", b =>
                {
                    b.HasOne("Research.Domain.Entity.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Research.Domain.Entity.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Skill");
                });
#pragma warning restore 612, 618
        }
    }
}
